---
- name: Check if geoipupdate is installed | Debian Stretch
  command: dpkg-query -W geoipupdate
  register: geoipupdate_check
  failed_when: geoipupdate_check.rc > 1
  changed_when: geoipupdate_check.rc == 1

- name: Add MaxMind PPA | Debian Stretch
  apt_repository:
    repo: maxmind_update_package_stretch_ppa
  when: geoipupdate_check.rc == 1

- name: Install Maxmind geoipupdate from PPA | Debian Stretch
  apt:
    name: maxmind_update_package_stretch
  when: geoipupdate_check.rc == 1
